image:
  file: .gitpod.Dockerfile

tasks:
  - name: Install Tools
    command: |
      brew install trivy
      brew tap interlynk-io/interlynk
      brew install sbomasm sbomqs
      brew install parlay
      brew install cosign
      curl -o /usr/bin/bnd -L https://github.com/carabiner-dev/bnd/releases/download/v0.0.1/bnd-v0.0.1-linux-amd64
      chmod 0755 /usr/bin/bnd 
  - name: Display Help
    command: |
      gp open README.md
